package rwt.bascat

import java.util.*

/**
 * A data class for Tokens
 * Created by richard todd on 10/9/2016.
 */
internal data class Token private constructor(val opcode:Int, val description:String) {
    internal companion object {

        fun fromOpcode(op:Int) : Token {
            return Token(op,  opcodes.get(op) ?: "<BAD OPCODE>" )
        }

        fun fromLiteral(lit:String) : Token {
            return Token(lit[0].toInt(), lit)
        }

        fun fromLiteral(lit:Char) : Token {
            return Token(lit.toInt(), Character.toString(lit))
        }

        fun fromNumber(num:Long, base:Int) : Token {
            return Token(-1,
                    when(base) {
                        8  -> String.format("&O%o", num)
                        16 -> String.format("&H%X", num)
                        else -> num.toString()
                    })
        }

        fun fromFloat(num:Double) : Token {
            return Token(-1, String.format("%G",num))
        }


        private val opcodes: HashMap<Int, String> = HashMap(200)
        init
        {
            opcodes.put(0x00, "EOL")
            opcodes.put(0x81, "END")
            opcodes.put(0x82, "FOR")
            opcodes.put(0x83, "NEXT")
            opcodes.put(0x84, "DATA")
            opcodes.put(0x85, "INPUT")
            opcodes.put(0x86, "DIM")
            opcodes.put(0x87, "READ")
            opcodes.put(0x88, "LET")
            opcodes.put(0x89, "GOTO")
            opcodes.put(0x8A, "RUN")
            opcodes.put(0x8B, "IF")
            opcodes.put(0x8C, "RESTORE")
            opcodes.put(0x8D, "GOSUB")
            opcodes.put(0x8E, "RETURN")
            opcodes.put(0x8F, "REM")
            opcodes.put(0x90, "STOP")
            opcodes.put(0x91, "PRINT")
            opcodes.put(0x92, "CLEAR")
            opcodes.put(0x93, "LIST")
            opcodes.put(0x94, "NEW")
            opcodes.put(0x95, "ON")
            opcodes.put(0x96, "WAIT")
            opcodes.put(0x97, "DEF")
            opcodes.put(0x98, "POKE")
            opcodes.put(0x99, "CONT")
            opcodes.put(0x9C, "OUT")
            opcodes.put(0x9D, "LPRINT")
            opcodes.put(0x9E, "LLIST")
            opcodes.put(0xA0, "WIDTH")
            opcodes.put(0xA1, "ELSE")
            opcodes.put(0xA2, "TRON")
            opcodes.put(0xA3, "TROFF")
            opcodes.put(0xA4, "SWAP")
            opcodes.put(0xA5, "ERASE")
            opcodes.put(0xA6, "EDIT")
            opcodes.put(0xA7, "ERROR")
            opcodes.put(0xA8, "RESUME")
            opcodes.put(0xA9, "DELETE")
            opcodes.put(0xAA, "AUTO")
            opcodes.put(0xAB, "RENUM")
            opcodes.put(0xAC, "DEFSTR")
            opcodes.put(0xAD, "DEFINT")
            opcodes.put(0xAE, "DEFSNG")
            opcodes.put(0xAF, "DEFDBL")
            opcodes.put(0xB0, "LINE")
            opcodes.put(0xB1, "WHILE")
            opcodes.put(0xB2, "WEND")
            opcodes.put(0xB3, "CALL")
            opcodes.put(0xB7, "WRITE")
            opcodes.put(0xB8, "OPTION")
            opcodes.put(0xB9, "RANDOMIZE")
            opcodes.put(0xBA, "OPEN")
            opcodes.put(0xBB, "CLOSE")
            opcodes.put(0xBC, "LOAD")
            opcodes.put(0xBD, "MERGE")
            opcodes.put(0xBE, "SAVE")
            opcodes.put(0xBF, "COLOR")
            opcodes.put(0xC0, "CLS")
            opcodes.put(0xC1, "MOTOR")
            opcodes.put(0xC2, "BSAVE")
            opcodes.put(0xC3, "BLOAD")
            opcodes.put(0xC4, "SOUND")
            opcodes.put(0xC5, "BEEP")
            opcodes.put(0xC6, "PSET")
            opcodes.put(0xC7, "PRESET")
            opcodes.put(0xC8, "SCREEN")
            opcodes.put(0xC9, "KEY")
            opcodes.put(0xCA, "LOCATE")
            opcodes.put(0xCC, "TO")
            opcodes.put(0xCD, "THEN")
            opcodes.put(0xCE, "TAB(")
            opcodes.put(0xCF, "STEP")
            opcodes.put(0xD0, "USR")
            opcodes.put(0xD1, "FN")
            opcodes.put(0xD2, "SPC(")
            opcodes.put(0xD3, "NOT")
            opcodes.put(0xD4, "ERL")
            opcodes.put(0xD5, "ERR")
            opcodes.put(0xD6, "STRING$")
            opcodes.put(0xD7, "USING")
            opcodes.put(0xD8, "INSTR")
            opcodes.put(0xD9, "'")
            opcodes.put(0xDA, "VARPTR")
            opcodes.put(0xDB, "CSRLIN")
            opcodes.put(0xDC, "POINT")
            opcodes.put(0xDD, "OFF")
            opcodes.put(0xDE, "INKEY$")
            opcodes.put(0xE6, ">")
            opcodes.put(0xE7, "=")
            opcodes.put(0xE8, "<")
            opcodes.put(0xE9, "+")
            opcodes.put(0xEA, "-")
            opcodes.put(0xEB, "*")
            opcodes.put(0xEC, "/")
            opcodes.put(0xED, "^")
            opcodes.put(0xEE, "AND")
            opcodes.put(0xEF, "OR")
            opcodes.put(0xF0, "XOR")
            opcodes.put(0xF1, "EQV")
            opcodes.put(0xF2, "IMP")
            opcodes.put(0xF3, "MOD")
            opcodes.put(0xF4, "\\")
            opcodes.put(0xFD81, "CVI")
            opcodes.put(0xFD82, "CVS")
            opcodes.put(0xFD83, "CVD")
            opcodes.put(0xFD84, "MKI$")
            opcodes.put(0xFD85, "MKS$")
            opcodes.put(0xFD86, "MKD$")
            opcodes.put(0xFD8B, "EXTERR")
            opcodes.put(0xFE81, "FILES")
            opcodes.put(0xFE82, "FIELD")
            opcodes.put(0xFE83, "SYSTEM")
            opcodes.put(0xFE84, "NAME")
            opcodes.put(0xFE85, "LSET")
            opcodes.put(0xFE86, "RSET")
            opcodes.put(0xFE87, "KILL")
            opcodes.put(0xFE88, "PUT")
            opcodes.put(0xFE89, "GET")
            opcodes.put(0xFE8A, "RESET")
            opcodes.put(0xFE8B, "COMMON")
            opcodes.put(0xFE8C, "CHAIN")
            opcodes.put(0xFE8D, "DATE$")
            opcodes.put(0xFE8E, "TIME$")
            opcodes.put(0xFE8F, "PAINT")
            opcodes.put(0xFE90, "COM")
            opcodes.put(0xFE91, "CIRCLE")
            opcodes.put(0xFE92, "DRAW")
            opcodes.put(0xFE93, "PLAY")
            opcodes.put(0xFE94, "TIMER")
            opcodes.put(0xFE95, "ERDEV")
            opcodes.put(0xFE96, "IOCTL")
            opcodes.put(0xFE97, "CHDIR")
            opcodes.put(0xFE98, "MKDIR")
            opcodes.put(0xFE99, "RMDIR")
            opcodes.put(0xFE9A, "SHELL")
            opcodes.put(0xFE9B, "ENVIRON")
            opcodes.put(0xFE9C, "VIEW")
            opcodes.put(0xFE9D, "WINDOW")
            opcodes.put(0xFE9E, "PMAP")
            opcodes.put(0xFE9F, "PALETTE")
            opcodes.put(0xFEA0, "LCOPY")
            opcodes.put(0xFEA1, "CALLS")
            opcodes.put(0xFEA4, "NOISE")
            opcodes.put(0xFEA5, "PCOPY")
            opcodes.put(0xFEA6, "TERM")
            opcodes.put(0xFEA7, "LOCK")
            opcodes.put(0xFEA8, "UNLOCK")
            opcodes.put(0xFF81, "LEFT$")
            opcodes.put(0xFF82, "RIGHT$")
            opcodes.put(0xFF83, "MID$")
            opcodes.put(0xFF84, "SGN")
            opcodes.put(0xFF85, "INT")
            opcodes.put(0xFF86, "ABS")
            opcodes.put(0xFF87, "SQR")
            opcodes.put(0xFF88, "RND")
            opcodes.put(0xFF89, "SIN")
            opcodes.put(0xFF8A, "LOG")
            opcodes.put(0xFF8B, "EXP")
            opcodes.put(0xFF8C, "COS")
            opcodes.put(0xFF8D, "TAN")
            opcodes.put(0xFF8E, "ATN")
            opcodes.put(0xFF8F, "FRE")
            opcodes.put(0xFF90, "INP")
            opcodes.put(0xFF91, "POS")
            opcodes.put(0xFF92, "LEN")
            opcodes.put(0xFF93, "STR$")
            opcodes.put(0xFF94, "VAL")
            opcodes.put(0xFF95, "ASC")
            opcodes.put(0xFF96, "CHR$")
            opcodes.put(0xFF97, "PEEK")
            opcodes.put(0xFF98, "SPACE$")
            opcodes.put(0xFF99, "OCT$")
            opcodes.put(0xFF9A, "HEX$")
            opcodes.put(0xFF9B, "LPOS")
            opcodes.put(0xFF9C, "CINT")
            opcodes.put(0xFF9D, "CSNG")
            opcodes.put(0xFF9E, "CDBL")
            opcodes.put(0xFF9F, "FIX")
            opcodes.put(0xFFA0, "PEN")
            opcodes.put(0xFFA1, "STICK")
            opcodes.put(0xFFA2, "STRIG")
            opcodes.put(0xFFA3, "EOF")
            opcodes.put(0xFFA4, "LOC")
            opcodes.put(0xFFA5, "LOF")
        }
    }
}
